[project]
name = "dependabot-notifications"
requires-python = ">=3.12"

dependencies = [
    "pyodide-build==0.30.9",
    "ruff==0.14.9",
]

[project.optional-dependencies]
dev = [
    "black==25.11",
    "poethepoet",
    "gersemi==0.24.0",
]
